### ISSUE TITLE
inet field support - Postgresql

### ISSUE THREAD

**Issue by iamazharsajjad** [activerecord-hackery/ransack#1068]
Error:
PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type inet: " 167.89.69.24"
ransack is not allowing me to search on type inet. Can anyone tell me why and how to over come this problem?

**Comment by JasonHerr** [comment]
Had the same question, here's what I found:

- https://github.com/activerecord-hackery/ransack/wiki/Using-Ransackers
- https://www.postgresql.org/docs/current/functions-net.html

So assuming you have an inet column called ip_address and you'd do this in your model class for that table:
``` ruby
ransacker :ip_address do
  Arel.sql('text(ip_address)')
end
```

**Comment by noeli1993** [comment]
@JasonHerr 

This fixed the problem of filtering -> ip_address_cont now works.

Did you figure out how sorting by ip_address with this modifaction works? 

Because with this the ip_address is sorted like a text. (Example ip_address ASC)
192.168.1.1
192.168.10.1
192.168.9.2

otherwise it would be:
192.168.1.1
192.168.9.2
192.168.10.1

which makes more sense.

**Comment by JasonHerr** [comment]
We stuck with the textual sort. It was good enough for customer needs. If pressed? I'd probably have to add a fake column for sorting like `select(*, 'ip_address as ip_address_sort')` and add it to the select and convert the params to sort on that column.
