### ISSUE TITLE
_in_all not working?

### ISSUE THREAD

**Issue by pctechjon** [activerecord-hackery/ransack#108]
I need to perform an exclusive (AND) search to return a list of Casinos that have any given Games at the casino.

Casino has many games.

Game belongs to casino.

I have a search form - I can set up an (OR) search just fine using 

``` erb
  <% @games.each do |a| %>
    <li><%= check_box_tag "q[games_id_in][]", a.id, false, :id => dom_id(a) %>

    <%= label_tag dom_id(a), a.name %>

    </li>
  <% end %>
```

However, when I try to make it "q[games_id_in_all][]" - it will only work with one check box marked. It will show the casinos that have that specific game. If you mark more than one, it will not show any results. I would expect it to take all of the IDs passed to it from the check box array, and fetch all of the casinos that have all of those games.

Here's my controller code on the results page:

``` ruby
  @search = Casino.ransack(params[:q])
  @casinos = @search.result(:disctinct => true).page(params[:page]).per(10)
```

Using Casino.ransack here because I have ActiveAdmin for the administrative back-end. (What I'm trying to do here is for the front end.)

**Comment by JWesorick** [comment]
+1 Same issue. I'm assuming it's because it is comparing each id with 2 ids. So no game has `id == 1 && id == 2`

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794
