### ISSUE TITLE
Sorting by an association's field

### ISSUE THREAD

**Issue by aq2-sanger** [activerecord-hackery/ransack#13]
I would like to be able to, e.g., pass in  'sorts = "user_name asc"' to sort by the user's name field.

Shouldn't be too hard to implement, should it?  Checking the logs, the join to the associated table already gets performed, so I'm assuming it'd be trivial to pass in the association's field name in the order(...) call as well?

**Comment by jonatack** [comment]
It seems to me that assocations are currently specified as `location.name` in the sort link and `location_name` everywhere else (search field, controller, rails console, etc.)

**Comment by dgm** [comment]
@jonatack No that's not  necessarily correct -  the sort link string is not a 1-1 mapping to an order clause spelling out sql.   It's a relation name, which may be a different table.    The documentation had me going totally the wrong direction on this.   The association section says,

'Please note that in a sort link, the association is expressed as an SQL string ('employees.last_name') with a pluralized table name, instead of the symbol :employee_last_name syntax with a class#underscore table name used for Ransack objects elsewhere.'

This appears to not be accurate.   In my case, I have a Request model that belongs_to a State model, which has a name attribute.   I was lead to believe by that statement that I should use:

`sort_link(@q, 'states.name')`

But found it only worked when I changed it to:

`sort_link(@q, 'state_name')`

**Comment by jonatack** [comment]
@dgm I am unable to reproduce this. Could you please provide the information mentioned in the Contributing Guide please?

**Comment by sauloperez** [comment]
Thanks for clarifying the docs @jonatack!

I wasn't sure if that still worked for a field of an association's association (A -> B-> C.field) and it does. [lib/ransack/adapters/active_record/context.rb#L209](https://github.com/activerecord-hackery/ransack/blob/feaebd5f9d32bba61e962121e0dc9de27005703e/lib/ransack/adapters/active_record/context.rb#L209) seems to be the method responsible for that.
