### ISSUE TITLE
How to create a Ransacker for HABTM searching?

### ISSUE THREAD

**Issue by burlesona** [activerecord-hackery/ransack#164]
My app has `photos` which have a habtm relationship with `terms` (terms are like tags). Here's a simplified explanation of what I'm experiencing:

I have two photos: Photo 1 and Photo 2. They have the following terms:

Photo 1: A, B, C

Photo 2: A, B, D

I built a ransack form using checkboxes, which does work but not the way I expected:

If I use: `q[terms_id_in][]` ...

and I check "A, C" my results are Photo 1 and Photo 2. I only want Photo 1, because I asked for A and C, in this query I don't care about B or D but I want both A and C to be present on a given result.

If I use: `q[terms_id_in_all][]` ...

and I check "A, C", my results are nil, because neither photo includes only A and C. Again, I want just Photo 1 to be returned.

If I use any variety of `q[terms_id_eq][]` I never get any results, so I don't think that works in this case.

So, given a habtm join, how do you search for models that match the given values while ignoring not given values?

---

Update: Given the results of my searching, I've found I can write a method that does produce the desired result:

```
def self.with_terms( array )
  select('distinct photos.*').joins(:terms).where('terms.id' => array).group("photos." + self.column_names.join(', photos.')).having("count(*) = #{array.size}")
end
```

Now, I see that you can make "ransackers" which are kind of like the "search methods" from meta_search. However, the specs etc. seem to indicate to me that ransackers are intended to be Arel stuff, which I'm not familiar with. Can anyone point out how you would convert the above method to a ransacker?

**Comment by nateberkopec** [comment]
After much pain, suffering, and blood sacrifice, I have discovered the sacred incantation:

```ruby
# I'm using Tags and Packages instead of Terms and Photos, but it's the exact same problem.

# In the view:
<%= check_box_tag('q[matches_all_tags][]', t.id, params["q"] && params["q"].fetch("matches_all_tags", []).include?(t.id.to_s) ) %>

# In package.rb
  scope :matches_all_tags, -> *tag_ids {
    where(matches_all_tags_arel(tag_ids))
  }

  def self.matches_all_tags_arel(tag_ids)
    packages = Arel::Table.new(:packages)
    tags = Arel::Table.new(:tags)
    packages_tags = Arel::Table.new(:packages_tags)
    packages[:id].in(
      packages.project(packages[:id])
        .join(packages_tags).on(packages[:id].eq(packages_tags[:package_id]))
        .join(tags).on(packages_tags[:tag_id].eq(tags[:id]))
        .where(tags[:id].in(tag_ids))
        .group(packages[:id])
        .having(tags[:id].count.eq(tag_ids.length))
    )
  end

  def self.ransackable_scopes(auth_object = nil)
    super + %w(matches_all_tags)
  end
```

**Comment by shreya** [comment]
@nateberkopec .. Sir, you saved my life with your solution. Thank you!!

**Comment by bo-oz** [comment]
As a small critique on this solution, it's not actually checking if a record in table A has the queried related records in table B. It's only checking if the amount of records returned by the query equals the amount of ID's supplied to the query. This could work in some situations, but fails when a record in table A has multiple relationships to the same record in table B. For instance, if record 1 from table A is related twice to record 2 from table B, then searching for record 2 and any other record results in displaying record 1. I'm still looking into fixing this... any help is appreciated.

**Comment by bo-oz** [comment]
Ok, I discovered that this Arel structure is based on this normal Rails command came up with by @fabn:

    Article.search(categories_id_in:[526,527,556]).result.group('articles.id').having('COUNT(categories.id) = ?', 3).to_sql

As I described in the previous command this could lead to unexpected results when 'an Atrticle' is related to the same Category multiple times (not a really logical use-case, but I stumbled upon one that is)

What you would like is to check the uniqueness of the unique count of the category_id in the join table in the 'having' part. So this would probably work:

    Article.search(categories_id_in:[526,527,556]).result.group('articles.id').having('COUNT(DISTINCT(article_categories.category_id)) = ?', 3).to_sql

(in which I'm guessing article_categories is the join table name)

I tested this and it seems to work, problem is I do not know how to adapt this into the Arel model... Any ideas?

**Comment by midhunkrishna** [comment]
to extend on @nateberkopec, 
say I have to filter a list of orders by their payment_types, say ['prepay', 'cash_on_delivery'], in ActiveAdmin, I do the following:

`filter :payment_type, as: :select, collection: ['prepay', 'cash_on_delivery']`

In order model:

```
class Order < AB

scope :prepay, -> { joins(...).where(...) }
scope :cash_on_delivery, -> { joins(...).where(...) }

scope :payment_type, -> (type) { Order.public_send(type)}

def self.ransackable_scopes(auth_object = nil)
    super + %w(payment_type)
 end
end

```

**Comment by svgr-slth** [comment]
Hello there!

I've experienced pretty much the exact same issue than people here, but just a few years later.
By the way thanks @nateberkopec for providing the scope.

Basically my goal is to get my models depending on tags like so: 
Models having tags (( A && B) ||  C) && ! D

Which is basically exactly what the advanced demo form is doing. But the AND part being not really compatible with HABTM or HMT relationships as we know, i ended up here and implemented that ransackable scope. But I'm wondering if its possible to make that scope work with the advanced example. Is there a way i can generate the `q` parameter so it ends up using this scope alongside other predicates on other fields, and in nested conditions like so, or is it simply impossible ? 

I have been trying a lot of stuff implementing new predicates that uses the scope but never found a way to make this work properly  generate a valid request in the end. 

My solution for now as dirty as it is is to keep a serialized version of the tags i associate to my model, inside the model itself and as a big string, so i can use the contains / contains_all / contains_any predicates to match my tags in that string and still using the nested grouping forms.

But it has an obvious limitation with tags that are similar or containing each other (e.g "north" / "north-east", if i want every model  tagged with "north" i end up with those + those tagged "north-east")

If anybody knows if its even possible, or if i can just give up looking for the solution that would already be something. 

Ransack is some awesome piece of work,  and basically the only open-source gem to make this happen out of the box, anybody wanting to implement a complex tagging system, that can be searchable with advanced queries will want that to work. And that's something you basically discover at the very end of the dev which can get frustrating of course so if not possible at all, i would put a disclaimer on the docs, and any ways i would put one just to make clear this case requires additional work for it to work, because when reading it through at the moment it really seems it's possible out of the box.
