### ISSUE TITLE
How to do search with OR between two ANDs

### ISSUE THREAD

**Issue by lironbeni** [activerecord-hackery/ransack#169]
I would like to use advanced search to create a query that looks something like this:

``` mysql
SELECT DISTINCT `cell_lines`.* FROM `cell_lines` 
INNER JOIN `chars` ON `chars`.`model_id` = `cell_lines`.`id` AND `chars`.`model_type` = 'CellLine' 
WHERE (cell_lines.deleted_at IS NULL) 
AND ((`chars`.`char_type_id` = 48 
AND `chars`.`value` LIKE '%run%'
OR `chars`.`char_type_id` = 39 
AND `chars`.`value` LIKE '%Be%'))
```

(note the OR at the end)
I catch the params[:q] before passing it to the ransack engine and do some manipulations on it so at the moment the best params[:q] I was able to produce is:

```
params[:q]
{
  "c"=>{
    "1353408836163"=>{
      "v"=>{"0"=>{"value"=>"48"}}, "p"=>"eq", "a"=>{"0"=>{"name"=>"chars_char_type_id"}}
    }, 
    "1353408836162"=>{
      "v"=>{"0"=>{"value"=>"run"}}, "p"=>"cont", "a"=>{"0"=>{"name"=>"chars_value"}}
    },
    "1"=>{
      "v"=>{"0"=>{"value"=>"39"}}, "p"=>"eq", "a"=>{"0"=>{"name"=>"chars_char_type_id"}}
    }, 
    "0"=>{
      "v"=>{"0"=>{"value"=>"Be"}}, "p"=>"cont", "a"=>{"0"=>{"name"=>"chars_value"}}
    }
  }
}
```

When passing this to ransack I get the following query:

``` mysql
SELECT `cell_lines`.* FROM `cell_lines` 
INNER JOIN `chars` ON `chars`.`model_id` = `cell_lines`.`id` AND `chars`.`model_type` = 'CellLine' 
WHERE (cell_lines.deleted_at IS NULL)
 AND ((`chars`.`char_type_id` = 39 
AND `chars`.`value` LIKE '%run%' 
AND `chars`.`char_type_id` = 48 
AND `chars`.`value` LIKE '%Be%'))
```

was trying to use Alter Lagos suggestion: http://stackoverflow.com/questions/12940629/make-an-or-with-ransack
but it replaced all the ANDs with ORs and this is not what I'm trying to accomplish....

Any suggestion would be appreciated..

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794
