### ISSUE TITLE
multi term search in one field

### ISSUE THREAD

**Issue by phron** [activerecord-hackery/ransack#218]
Not an issue I suppose but a lack of information/documentation on this... 
I wiould like to do something like that :

``` ruby
 User.search({:profile_last_name_or_profile_first_name_cont_any=> 'jane doe'.split(' ')}).result
```

the SQL generated is the following

``` ruby
"SELECT "users".* FROM "users" LEFT OUTER JOIN "profiles" ON "profiles"."user_id" = "users"."id" WHERE ((("profiles"."last_name" ILIKE '%jane%' OR "profiles"."last_name" ILIKE '%doe%') OR ("profiles"."first_name" ILIKE '%jane%' OR "profiles"."first_name" ILIKE '%doe%')))"
```

which returns the expected results... But how to implement this request in my search form (in my view) and/or in my controller ?

My search form is :

``` ruby
<%= search_form_for @q, url: search_cockpit_users_path, method: 'post', id: 'users-search-form', class: 'span3 pull-right' do |su| %>
      <%= su.text_field :profile_last_name_or_profile_first_name_or_email_cont_any, :placeholder => 'full name or email contains' %>
      <%= su.submit 'Search', :name => nil, :class => 'btn ' %>
  <% end %>
```

As it is the SQL returned is

``` ruby
"SELECT "users".* FROM "users" LEFT OUTER JOIN "profiles" ON "profiles"."user_id" = "users"."id" WHERE ((("profiles"."last_name" ILIKE '%jane doe%') OR ("profiles"."first_name" ILIKE '%jane doe%')))"
```

but how to implement the split(' ') to have the expected SQL ?

Any help (and a bit of explanation) would be great, documentation is a bit light on the subject...

Cheers

**Comment by bverem** [comment]
Just curious if this was resolved. I'm also noticing a disparity between how the form method generates SQL for ```cont_any``` on multiple fields and how the ransack method generates SQL.

In my example, the expected behavior (console):

```
Model.ransack(submitter_name_or_tags_name_cont_any: %w(example tooth)).result.to_sql
=> "SELECT `cases`.* FROM `cases` LEFT OUTER JOIN ... WHERE ((`users`.`name` LIKE '%example%' OR `users`.`name` LIKE '%tooth%') OR (`tags`.`name` LIKE '%example%' OR `tags`.`name` LIKE '%tooth%'))"
```

The behavior when using  ```:submitter_name_or_tags_name_cont_any``` within ```search_form_for``` with the setup used in the readme/wiki:
```
SELECT  `cases`.* FROM `cases` LEFT OUTER JOIN ... WHERE ((`users`.`name` LIKE '%example tooth%') OR (`tags`.`name` LIKE '%example tooth%'))
```

I followed something similar to the instructions above that alter the params, but I'm running into difficulties getting the altered params through will_paginate. I can get it to work by using ```params: params.permit!``` on my will_paginate helper, but that is certainly not my preference. I tried looking through the source code for this gem to see if there are ways to make the search form work like the console with no luck. Any thoughts? Is there any way I can make a search form use the same behavior as the console? Other than that, this gem is pretty fantastic. Thank you for all you do!

**Comment by sasharevzin** [comment]
> @AnSo, your controller fills in `params` variable (Hash)
> 
> your form use `@q` to store search params, which is fine
> 
> here is a workaround for `any`
> 
> ```ruby
> # a bit dirty code
> params[:q][:combinator] = 'or'
> params[:q][:groupings] = []
> custom_words = params.delete('profile_last_name_or_profile_first_name_or_email_cont_any')
> custom_words.split(' ').each_with_index do |word, index|
>   params[:q][:groupings][index] = {profile_last_name_or_profile_first_name_or_email_cont: word} 
> end
> 
> @q = User.joins(:profile).search(params[:q])
> @users = @q.result.paginate(:per_page =>10, :page => params[:page])
> ...
> ```

In this case, the form with `profile_last_name_or_profile_first_name_or_email_cont_any` field will be empty. It won't show what was in the field before sending the form

**Comment by kaka-ruto** [comment]
Mine worked with
` User.ransack(profile_last_name_or_profile_first_name_in: params[:keywords].split(',  ')).result`
