### ISSUE TITLE
Ability to search with dynamic Arel attributes

### ISSUE THREAD

**Issue by pusewicz** [activerecord-hackery/ransack#237]
I don't think there is a way to let the search use Arel for the values.

I would love to be able to do something in the lines of:

``` ruby
Incident.search(assignee_id_eq: Incident.arel_table[:requester_id])
```

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794
