### ISSUE TITLE
missing interpolation argument :attributes

### ISSUE THREAD

**Issue by johnrees** [activerecord-hackery/ransack#310]
I've just started adding translations to my rails app with the localeapp gem, all it does is manage your locale yml files. Anyway, I'm suddenly getting errors like this -

`missing interpolation argument :attributes in "%{attributes}" ({:count=>1, :attr_fallback_name=>"%{attributes}"} given)`

on sort_links that have been working fine up until now e.g.

`sort_link @q, :id`

My head is spinning at the moment, I'll try and take a proper look at it tomorrow but thanks in advance if anyone can give me some pointers.

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794
