### ISSUE TITLE
Handle special characters

### ISSUE THREAD

**Issue by grillorafael** [activerecord-hackery/ransack#332]
Hi, guys!

I'm having a problem here.

I have a record with the following name: 'Pão de Ló'

When I search for 'p', I get my result fine but when I search for 'pa' I get no results.

Is there any way to match these characters?

**Comment by guilpejon** [comment]
Since I lost a couple of hours with this issue today, I'm going to share what I had to do to make the proposed solution work. I'm using PostgreSQL

```ruby
# on initializers/ransack.rb
Ransack.configure do |config|
  config.add_predicate 'special_match', # Name your predicate
      arel_predicate: 'matches',
      formatter: proc { |v| ActiveSupport::Inflector.transliterate("%#{escape_wildcards(v)}%") },
      validator: proc { |s| s.present? },
      compounds: true,
      type: :string
end
# replace % \ to \% \\
def escape_wildcards(unescaped)
  case ActiveRecord::Base.connection.adapter_name
  when "Mysql2".freeze, "PostgreSQL".freeze
    # Necessary for PostgreSQL and MySQL
    unescaped.to_s.gsub(/([\\%_.])/, '\\\\\\1')
  else
    unescaped
  end
end
```

As for the database part, I used another solution, from #349 

```ruby
ransacker :name, type: :string do
  Arel.sql("unaccent(\"name\")")
end
```

Note that you have to add the unnacent postgres extension for this to work
```ruby
class AddUnnacentExtension < ActiveRecord::Migration[5.0]
  def up
    execute 'CREATE EXTENSION IF NOT EXISTS unaccent;'
  end

  def down
    execute 'DROP EXTENSION IF EXISTS unaccent CASCADE;'
  end
end
```

**Comment by llekn** [comment]
Since I lost a couple of hours too I would like to share my solution.

As I wanted to add the capability to use `unaccent` in multiple places and in complex queries (search in multiple columns, for example), adding a ransacker as proposed in the previous post wouldn't solve my problem.

What I ended doing (and ended working 😄 ) was:


**Add the [`arel_extensions`](https://github.com/Faveod/arel-extensions) gem.**

This gem adds a lot of interesting new nodes and predicates for `Arel`, in particular it adds the `ai_imatches` predication that enables a case-insensitive and accent-insensitive matcher search.

```ruby
gem 'arel_extensions'
```


**Create a new ransacker predicate that uses this Arel predication in `app/config/initializers/ransack.rb`**:

```
Ransack.configure do |config|
  config.add_predicate(
    # produces queries in the form of `WHERE (unaccent (column)) ILIKE unaccent (%foo%bar%)`
    'ucont',
    arel_predicate: 'ai_imatches', # <- thanks arel_extensions !
    formatter: proc { |s| ActiveSupport::Inflector.transliterate("%#{s.tr(' ', '%')}%") },
    validator: proc { |s| s.present? },
    compounds: true,
    type: :string
  )
end
```
(the replacement of spaces by `%` will be helpful for matching space separated words with multiple columns)


**From now on you can use the `ucont` predicate on every ransack!**

You can also create a `ransacker` for unaccented, case-insensitive, space separated words in multiple columns. For example:

```ruby
  ransacker :full_name do |parent|
    Arel::Nodes::InfixOperation.new(
      '||',
      parent.table[:first_name],
      Arel::Nodes::InfixOperation.new(
        '||',
        parent.table[:last_name],
        parent.table[:middle_name]
      )
    )
  end

```

Then in some view you can do

```
<%= f.search_field :full_name_ucont %>
```

🎉

**Comment by jmarsto** [comment]
I noticed that this broke down with NULL middle (or other) names.  To avoid this, one can concatenate first middle last:

``` 
  ransacker :full_name do |parent|
    Arel::Nodes::NamedFunction.new(
      'CONCAT_WS',
      [
        Arel::Nodes::Quoted.new(' '),
        parent.table[:first_name],
        parent.table[:middle_name],
        parent.table[:last_name]
      ]
    )
  end
```
