### ISSUE TITLE
Rails 4.1.1 scope named 'search' conflict with Ransack.

### ISSUE THREAD

**Issue by phallstrom** [activerecord-hackery/ransack#369]
I just ran into an error with 4.1.1 and ransack.  I don't use ransack myself, but activeadmin does apparently.  I have a scope on an AR model named 'search'.  Starting my rails app would result in the following error:

```
activerecord-4.1.1/lib/active_record/scoping/named.rb:143:in `scope': You tried to define a scope named "search" on the model "MyModel", but Active Record already defined a class method with the same name. (ArgumentError)
```

4.1.1 will now complain if you try to use a scope name it considers dangerous.  Dangerous is defined as any method name already defined by ActiveRecord::Base.  Here's the git commit for it:

https://github.com/rails/rails/commit/7e8e91c439c1a877f867cd7ba634f7297ccef04b

Took me awhile to find it since AR doesn't define 'search' anywhere.  Ransack does though:

```
alias :search :ransack unless base.respond_to? :search
```

https://github.com/activerecord-hackery/ransack/blob/master/lib/ransack/adapters/active_record/base.rb#L7

I'm guessing that ActiveAdmin doesn't use 'search' directly since this all worked in Rails 4.0.5 using my model's search method and ActiveAdmin on the same model.

Not sure what the right solution is since ransack wouldn't know about my scope name until it's too late and I'm sure most of your user's use 'search'.  Maybe not.

I found the following to work if placed in a config/initializer file.

```
Ransack::Adapters::ActiveRecord::Base.class_eval('remove_method :search')
```

**Comment by jfragoulis** [comment]
> With Rails 4.1.1 you can't have a scope that has the same name as any method in AR::Base. So, the net effect is that if you use ransack you can't have 'search' as a scope in any model.

Can please someone point me to the respective rails PR????

**Comment by jfragoulis** [comment]
To answer my own question https://github.com/rails/rails/issues/13389

**Comment by K1N5L4Y3R** [comment]
I can confirm that to this day (ransack 2.1.1, rails 6.0.0, activeadmin 2.6.1), having existing `::search` scopes declared in one or more Rails models and using ransack via ActiveAdmin gives this error.

The simple fix is to change the existing `::search` scope name on your model(s) to something like `::own_search` when possible.
However, I would agree that having the ability to configure the name of the scope used would be a nice benefit (please let me know if there's a way of achieving this, since I couldn't find it).
