### ISSUE TITLE
Two typos in the doc

### ISSUE THREAD

**Issue by v5out** [activerecord-hackery/ransack#468]
Ransack is great! Cleaning up a few typos in the doc would help a bit, too. The two that got me today were:

  <%= content_tag :th, sort_link(@q, 'departments.title') %>
  <%= content_tag :th, sort_link(@q, 'employees.last_name') %>

I believe those should be _ (underscores) instead of "." and supervisor belongs_to department so that should be 'department_title'.

**Comment by dgm** [comment]
As I commented on #13, the documentation is wrong.   the sort link string appear to not map directly to sql.   It works as `department_title` but not as `departments.title` or `department.title`

**Comment by jonatack** [comment]
@dgm I am unable to reproduce this. Could you please provide the information mentioned in the Contributing Guide please?

**Comment by dgm** [comment]
Here's a basic rails app that implements the documentation.

https://github.com/dgm/ransack-sort-demo

As you can see, the links as documented do not work, but I provide other links that do.

The basic misconception seems to be in thinking that 'the association is expressed as an SQL string' ...   It most assuredly is not.  It uses the same association name underscore attribute format as all the rest of the searchers. (minus a predicate like _cont).

**Comment by jonatack** [comment]
Could you begin by providing the basic info in the Contributing Guide so that we can try to reproduce your environment? It's not practical to guess which Ruby, Rails and Ransack versions you are using. I'm not saying you're wrong, but I have to reproduce your environment and issue.

**Comment by dgm** [comment]
The Gemfile and Gemfile.lock should have all that info.  

Rails 4.2, ruby 2.1 or ruby 2.2 , it won't matter.

ransack (1.5.1)

**Comment by jonatack** [comment]
I don't see where the Ruby or Ransack version was specified in the demo app. Please don't make people guess. Are you encountering the issue with the latest Ransack release (1.6.3)?

**Comment by dgm** [comment]
Gemfile.lock  always has that info for rails apps.    Anyway, no change on 1.6.3

**Comment by dgm** [comment]
And I don't think there should be any change - the current behavior is correct, it uses the existing association to generate the sort - which may include special conditions  into the overall sql.   sorting on a simple sql table.column is way too simplistic for what ransack actually does.   The documentation is just wrong.

**Comment by jonatack** [comment]
How are you testing this issue?

**Comment by dgm** [comment]
I meant to commit the sqlite database with that so the test data is there...   pull the latest changes, run the rails server and look at http://localhost:3000/supervisors

**Comment by AdamFerguson** [comment]
@dgm Thanks, I wasn't able to get sort_link's working on associations according to the documentation using the `'plural_table_name.column_name'` convention but using the `'association_column'` convention you suggested worked.

**Comment by jacwellington** [comment]
@dgm I experienced the same behavior in 1.6.6. I needed to do `'association_column'` to get it to work. The way the docs say to do it doesn't work.

**Comment by UlyssesInvictus** [comment]
I know it's pouring oil on the fire at this point, but I experienced the same behavior with 1.7.0. The SQL doesn't work at all, in any form or pluralization, but a symbolized underscore works great.

**Comment by jonatack** [comment]
Thanks @UlyssesInvictus, could you provide actionable information to reproduce? Version of Active Record, Ruby, which database? Are you using Ransack via another gem like Active Admin? Is it not working the same on the command line as in your app?

**Comment by jonatack** [comment]
I'd like to understand how/when people are running into this. In the meantime, I've committed a change in the docs that provides both versions.

**Comment by jonatack** [comment]
In #13, Ernie states at the top of the thread to use a string, as did the docs.

I'd like to understand how/when people are having this issue.

In the meantime, I've committed a change in the docs that provides both versions.

**Comment by dgm** [comment]
As I see it, it is not an sql string at all, but the association, just like "Ransack objects elsewhere"  as the removed part of your commit above said...  if the association is a belongs_to, it will be singular, and underscores to seperate parts.... *just like ransack objects elsewhere*

**Comment by jonatack** [comment]
I agree that it should be like that, but have not been able to reproduce... only SQL-style strings work for sort links on associations for me. I don't use Active Admin or Simple Form -- all standard omakase Rails. Perhaps I'm doing something in my code that no one else is doing :cactus: 

This afternoon I have to step through the sort link code with byebug/pry to work on Ransack breaking with Rails master now that strong parameters inherit from ActionController::Parameters now. Lots of things are breaking from this... it's pretty bad. Perhaps I'll see what's going on with the associations while I'm at it. Otherwise will look through your example app above.

**Comment by UlyssesInvictus** [comment]
Oh, sorry, forgot many crucial details--that's so odd that it breaks for you in the opposite way it breaks for everyone else.

Anyways, I was running:
- Ruby 2.2.2
- Rails (and ActiveRecord) 4.2.3
- MySQL
- in both the console and directly from the view/controller
- Ransack by itself (though I can't speak for its own dependencies, since I just naively installed it with bundler)
- A basic structure of `Model A belongs_to Model B`, where I wanted to `sort_link query, :b_attribute`, where `query` was created with `a_instances.ransack`. `:b_attribute works`, but `'bs.attribute'` and `'b.attribute'` both fail silently. (I also made sure I was `.includes(:b)`-ing every time.)

**Comment by jonatack** [comment]
Thanks. Not sure it is the opposite for everyone else, 2 million downloads of Ransack and ten people mention a problem. It could have been people using Active Admin (which modifies the Ransack API) or using another database like Sequel instead of Active Record. But I'm willing to believe it might be something on my side until I really go through it.

**Comment by UlyssesInvictus** [comment]
No, of course--should have clarified "everyone else [in this thread]."
