### ISSUE TITLE
sort by sub select field

### ISSUE THREAD

**Issue by u007** [activerecord-hackery/ransack#484]
example:
@q = Job.select("(select count(distinct id) from job_applications where job_id=jobs.id) as app_count")
@q[:s] = "app_count desc"

**Comment by d4be4st** [comment]
I would need this also.
Example:

I have a scope which defines a complicated function

```
scope :max_price, -> (price) { select('ships.*, MAX(COALESCE(sailings.price, season_ships.price)) as max_price').group('ships.id').having('max_price < ?', price) }
```

I do not want to use ransackers as I want to user 'max_price' in my view, without going to the database but i can not sort by that field...

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794
