### ISSUE TITLE
f.select postback

### ISSUE THREAD

**Issue by travisvalentine** [activerecord-hackery/ransack#54]
Hi Ernie,

Happy Holidays to you. I'm new to programming and using Ransack in my Rails 3 app. It's working great, though I have a question about using `<%= f.select %>` in a form that I submit using jQuery. (I'm not sure if this is actually a problem with my use of Ransack or not.)

As described in the docs, here are the actions in my Controller where I'm performing the search:

```
def index
  @q = User.search(params[:q])
  @users = @q.result(:distinct => true)
end

def search
  index
  render :index
end
```

Here's my select helper: 

```
<%= f.select :profile_subject_eq, options_for_select([['Select', ''], ['Arts'], ..., ['Vocational']], @q)  %>
```

I'm using the following jQuery to submit the search form:

```
$(function(){
    $('select').live('change',function() {
        $(this).closest('form#index').submit();
    });
});
```

The problem is that when I select an option, the form is submitted, but the post back value isn't the value that initiated and returned the search results. I believe it just defaults to "Select". Any help would be much appreciated.

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794
