### ISSUE TITLE
Search through columns with underscores in name

### ISSUE THREAD

**Issue by RoblesCoulter** [activerecord-hackery/ransack#579]
Hello,

I'm trying to add an extra column to the search field and the column name is "box_number" when I add it to the search field I doesn't add it to the search parameters.

```ruby
<%= search_form_for @q, url: boxes_path, html: { method: :get, class: "form-inline form-main-search", id: "ajax_search" } do |f| %>
	<div class="form-group">
		<%= f.search_field :box_number_or_barcode_or_description_or_location_name_or_location_country_or_condition_name_cont, class:"form-control" %>
		<%= f.submit "Search", :name => nil, class: "increased-width btn btn-primary" %>
	</div>
	<div id="ajax_objects" ><%= render 'boxes' %></div>
<% end %>
```

**Comment by gpcweb** [comment]
Same problem here.. How can I search in a column that has an underscore on it??

**Comment by jonatack** [comment]
Though neither of you provided a gist or test case, which forces us to guess... I will guess. Underscore should work. The first case might be because the OP mixed his types, with integer columns and string columns in the same query. This used to work, provided the query did not begin with an integer column but with a string column, but since Rails 4.2 (I believe) the coercion of integers to strings is no longer automatic. The second case, where no reproducible code is provided at all, it could be anything. Sorry for not trying to guess further ;)

**Comment by gpcweb** [comment]
Sorry for making to waste your time @jonatack.. it was this line:

`self.whitelisted_ransackable_attributes =  %w[completed_at created_at email number state payment_state shipment_state total considered_risky]`

Inside of this file [https://github.com/spree/spree/blob/master/core/app/models/spree/order.rb](url)

The solution was to make a spree order decorator.

**Comment by jonatack** [comment]
@gpcweb Thanks for reporting back!

**Comment by RoblesCoulter** [comment]
Hi @jonatack, sorry I did not provide further information, the problem was actually the difference between the string and integer columns. 

Thank you very much!

**Comment by jonatack** [comment]
@RoblesCoulter Excellent. Thank you!
