### ISSUE TITLE
Combine several fields in search

### ISSUE THREAD

**Issue by marco-martins** [activerecord-hackery/ransack#59]
It´s possibility combine several fields, for exemple text input to search NAME and ID like this:

<%= f.text_field "name_cont_or_id_eq", :placeholder => "Search" %>

Many thanks.

**Comment by thirdsun** [comment]
I'm sorry to post in this old thread, but I have an issue that fits in here and couldn't find an answer in the docs or the wiki. 
I'm aware of the `first_name_or_last_name_or_email_cont` syntax, however similar to @skarface I'd like to combine `cont`and `eq` in one query/search input. Furthermore the columns to be searched are of different type. Basically I'd like to have a quick search input where a user can either input a name or the full id of the wanted record.
Something like `name_cont_or_id_eq`- however it seems that if I want to search multiple columns with an `OR` or `AND` operator I have to settle either for `cont`or `eq`. A combination of both doesn't seem to be possible unlesse I'm missing something.

On a sidenote, I think the documentation is rather lacking when it comes to more complex queries. And this very issue should probably be a simple one.
There are lots of code examples in the Wiki, but they aren't explained very well - I have a hard time understanding the concepts.

**Comment by jonatack** [comment]
Hi @thirdsun, anyone can edit the wiki; please feel free to update it to clarify anything you find lacking. Ransack is free, open-source software that everyone can contribute to and the best way to shape it to your needs is to do just that. Cheers :smiley:

**Comment by jonatack** [comment]
P.S. - I would use two different search fields, one for id searches and one for `first_or_last_or_email_cont`, etc. I suppose you could combine the two with a `ransacker` method using Arel if it was absolutely necessary.

**Comment by jonatack** [comment]
The caveat with combining them is that you'll slow your db queries down a lot. I've mentioned this simple performance technique for multi-column searches in one field a few times here in Ransack issues, but here it is again:

Create a search string column in the database table, updated with a before_save callback in your model or in SQL, that combines in one string column the essential fields you want to search by, each separated by a special character. Create a db index on that column, and with Ransack search just on that one column `search_string_cont`. The SQL queries will be much faster and your code much simpler.

**Comment by thirdsun** [comment]
Hi @jonatack - I did not intend to sound rude or expect you to do the work. Of course I'm aware that everyone can change the wiki - including me. However since I didn't completely understand the advanced concepts of Ransack yet, I may not be all that qualified for that task. 

Yes, splitting the search fields would make things easy - however I don't like that idea from a UI perspective. 

The other suggestion would take care of that problem, but I'm not sure if I like to use a special column for this purpose. I'd like to think of the database as pure source of raw data - this isn't a huge issue though, I'll consider it.

Again, I didn't mean any offense concerning the docs, just pointing out my impression.

**Comment by ashr81-rg** [comment]
@michaelfeihstel  Did you find any solution for this issue?

**Comment by michaelfeihstel** [comment]
@ashr81-rg Not with Ransack as I didn't want to split the search fields. However the pg_search gem allowed me to build a global search feature: https://github.com/Casecommons/pg_search

**Comment by saurabh-prohaktiv** [comment]
I too would like to know if I can have `name_cont_or_id_eq`, is it possible now as I am not able to find any document regarding that.

I was able to achieve the above by adding the code below
```
q = params[:q]
search_params = { id_eq: q, name_cont: q, m: 'or' }
```
However the problem is, I want to add `AND` operator for some other fields as well now but specifying `m: 'or'` is not allowing me to do that.
