### ISSUE TITLE
JSONB column using custom operator

### ISSUE THREAD

**Issue by gabeodess** [activerecord-hackery/ransack#624]
How would I construct a query using a custom operator with Ransack?

For example, if I want to use the containment operator for a JSONB column:

    WHERE people.address @> '{"borough":"manhattan"}'::jsonb

This would be ideal because it makes use of the GIN index.  However, if this is not possible with Ransack, what about something like this:

    WHERE people.address -> 'borough' ? 'manhattan'

I realize I can setup the first part of the query with this:

    ransacker :borough do
        Arel.sql(" people.address -> 'borough' ")
    end

But how do I get the "?" operator in there?

**Comment by jonatack** [comment]
Hi @gabeodess, I haven't tried using Ransack with a JSONB column. Perhaps you're looking for a [custom predicate](https://github.com/activerecord-hackery/ransack/wiki/Custom-Predicates)? If you can implement the query via Arel and/or with a custom predicate, it should theoretically be possible.

If this isn't a strictly a bug in Ransack, I'd prefer not to keep it open in the issue tracker and would suggest posting it on Stack Overflow as well where a larger community can help. If it turns out to be a feature request, the best would be to make a PR. Cheers.

**Comment by jonatack** [comment]
A quick search in the Ransack issues turned up this: https://github.com/activerecord-hackery/ransack/issues/453. Closing.
