### ISSUE TITLE
can I use sort_link without changing sort condition?

### ISSUE THREAD

**Issue by xiaok** [activerecord-hackery/ransack#667]
```
<%= sort_link(@q, :like_count, 'hot topic', default_order: :desc, hide_indicator: true) %>
```

I don't want to chage sort condition from :desc to :asc when I click this link

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794
