### ISSUE TITLE
Presence operator raises exception when used with datetimes 

### ISSUE THREAD

**Issue by why-el** [activerecord-hackery/ransack#695]
`User.ransack(created_at_present: 1).result`

Will fail with an exception: 

`ActiveRecord::StatementInvalid: PG::InvalidDatetimeFormat: ERROR:  invalid input syntax for type timestamp: ""`

in Postgresql. This is because `created_at != ''` is not valid PG syntax. This is similar to https://github.com/activerecord-hackery/ransack/issues/641, but because this actually fails with an exception I think it has higher severity.

**Comment by danieldocki** [comment]
@why-el found any solution for this?

**Comment by why-el** [comment]
@danieldocki not directly no, but I think we combined an html select and the :null operator, and it worked.

**Comment by jonatack** [comment]
This seems like a use case for a ransacker method. If it is a commonly-needed feature that users would really like to have added into Ransack, I'll be happy to review a pull request.

**Comment by pharmmd-rich** [comment]
I just got bit by this as well.  Use case:  We have a deactivated_at timestamp.  If there is a value set, the user is considered deactivated.  if no value is set (nil), the user is considered active.

**Comment by danieldocki** [comment]
I think the view must deal with this.

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794
