### ISSUE TITLE
use mongoid and activerecord

### ISSUE THREAD

**Issue by kkyouhei** [activerecord-hackery/ransack#697]
I use mongoid and activerecord and I want to find in mongo.
But I can't use ransack... because of https://github.com/activerecord-hackery/ransack/blob/master/lib/ransack/adapters.rb#L8
Does switch options exist ?

**Comment by jonatack** [comment]
Hi @kkyouhei, you can override `Ransack::Adapters#instantiate_object_mapper` to add your own custom logic. As per the readme:

"NOTE: Ransack currently works with either Active Record or Mongoid, but not both in the same application. If both are present, Ransack will default to Active Record only. The logic is contained in Ransack::Adapters#instantiate_object_mapper should you need to override it."

If this turns out to be something that many people need, I'm open to a pull request to add it as a Ransack config option.

To be honest, I don't use MongoDB and do not maintain the Mongoid adapter in Ransack, so any maintenance to it that you or the community can contribute would be very welcome.
