### ISSUE TITLE
Wrong scope methods arity get

### ISSUE THREAD

**Issue by zhangsoledad** [activerecord-hackery/ransack#698]
https://github.com/activerecord-hackery/ransack/blob/master/lib/ransack/context.rb#L56

``` ruby
def scope_arity(scope)
  @klass.method(scope).arity
end
```

There are no explicit parameters for scope methods, because 

``` ruby
def scope(name, body, &block)
   ........
  extension = Module.new(&block) if block

  singleton_class.send(:define_method, name) do |*args|
    scope = all.scoping { body.call(*args) }
    scope = scope.extending(extension) if extension

    scope || all
  end
end
```

call `scope_arity` with scope methods will always return -1
kind of a hack implementation:

``` ruby
def scope_arity(scope)
  @object.public_send(scope)
  0
rescue ArgumentError => e
  f = e.message.scan(/for\s+(\d+)/).flatten.first
  f.to_i.nonzero? || 0
end
```

BTW
https://github.com/activerecord-hackery/ransack/blob/master/lib/ransack/search.rb#L134,
I don't think Ransack should be responsible for converting params anymore,this make many unexpected behavior happen when use scope

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794
