### ISSUE TITLE
Allow custom URL in sort_link

### ISSUE THREAD

**Issue by psyren89** [activerecord-hackery/ransack#713]
Relatively new Rails dev here, so bear with me if I explain things poorly or use incorrect terminology.

My routes look like this:
```
resources :discount_tokens, except: :show do
  collection do
    get :active, action: :index, defaults: {active: true}
    get :expired, action: :index, defaults: {expired: true}
    get :redeemed, action: :index, defaults: {redeemed: true}
  end
end

  active_admin_discount_tokens GET       /admin/discount_tokens/active(.:format)                                                         admin/discount_tokens#index {:active=>true}
 expired_admin_discount_tokens GET       /admin/discount_tokens/expired(.:format)                                                        admin/discount_tokens#index {:expired=>true}
redeemed_admin_discount_tokens GET       /admin/discount_tokens/redeemed(.:format)                                                       admin/discount_tokens#index {:redeemed=>true}
         admin_discount_tokens GET       /admin/discount_tokens(.:format)                                                                admin/discount_tokens#index
```

and my view looks like this:
```
%th= sort_link(@ransack_query, :discount_percentage, "Discount")
%th= sort_link(@ransack_query, :expires_at)
```

My problem is that all the links generated by `sort_link` point to the `active` path, no matter which path I'm currently on:
```
sort_link(@ransack_query, :discount_percentage, "Discount")
"<a class=\"sort_link \" href=\"/admin/discount_tokens/active?q%5Bs%5D=discount_percentage+asc\">Discount</a>"
sort_link(@ransack_query, :expires_at)
"<a class=\"sort_link desc\" href=\"/admin/discount_tokens/active?q%5Bs%5D=expires_at+asc\">Expires at&nbsp;&#9660;</a>"
```

Would it possible to allow a path/url to be specified as an argument to `sort_link`?

**Comment by jonatack** [comment]
Hello! To help us help you, could you provide a standalone gist to reproduce your issue? See  [CONTRIBUTING.md](https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md) for more information and a bug report template to work from.

For questions/personal support, please use StackOverflow, where a wider community will be able to help you. We try to reserve the issues tracker for issues (bugs) with Ransack itself.

Closing, will re-open if actionable info is provided. Thanks!

**Comment by jgadbois** [comment]
I also would like to be able to specify a different url in a `sort_link` call

**Comment by jordanmaguire** [comment]
Old topic. I ran into this recently and solved it so I'll put that info here.

Under the hood, `#sort_link` just falls back to Rails' [`url_for`](https://apidock.com/rails/ActionView/RoutingUrlFor/url_for) method. It passes your options directly in as a hash.

From the code:

1. https://github.com/activerecord-hackery/ransack/blob/master/lib/ransack/helpers/form_helper.rb#L54
2. https://github.com/activerecord-hackery/ransack/blob/master/lib/ransack/helpers/form_helper.rb#L133

So if you did:

`sort_link(@query_object, :attribute_name, param_key: "param_value")`

The URL you get will append `param_key=param_value` to your query string via `url_for`.

When using routes that use the same controller and action as in the example above, I don't actually think it is possible to generate any of your other named routes via `url_for`.

Instead, to solve this issue, I think you can pretty easily have your routes correspond to different actions so that `url_for` can generate your routes.

You would change the routes above by removing the index action:

```ruby
resources :discount_tokens, except: :show do
  collection do
    get :active, defaults: {active: true}
    get :expired, defaults: {expired: true}
    get :redeemed, defaults: {redeemed: true}
  end
end
```

and in your controller, just alias the `index` method:

```ruby
class DiscountTokensController
  def index
    # whatever you already had
  end

  alias_method :active, :index
  alias_method :expired, :index 
  alias_method :redeemed, :index
end
```

now your sort link will work.
