### ISSUE TITLE
Ransack - deep association sorting

### ISSUE THREAD

**Issue by qrooel** [activerecord-hackery/ransack#716]
Original stackoverflow link: 
http://stackoverflow.com/questions/39139254/ransack-deep-association-sort-link-not-working

Hello,
I am trying to sort column using Ransack, but with no luck.

Model Application

```
class Application < ActiveRecord::Base
  has_many :orders
end
```

Model Order

```
class Order < ActiveRecord::Base
  belongs_to :executor_group, class_name: "Group"
end
```

Model Group

```
class Group < ActiveRecord::Base
  has_many :orders, foreign_key: "executor_group_id"
end
```

Having those models, I am trying to sort like this (from application model/controller):

`sort_link(search, :orders_executor_user_last_name, translation)`

Controller search operation:

```
@search = Application.includes(:group).search(search_params)
@applications = @search.result.paginate(pagination_params)
```

Generated SQL:

`SELECT`applications`.* FROM`applications`LEFT OUTER JOIN`orders`ON`orders`.`application_id`=`applications`.`id`LEFT OUTER JOIN`groups`ON`groups`.`id`=`orders`.`executor_group_id`ORDER BY`groups`.`name`DESC LIMIT 20 OFFSET 0`

So, I want to sort applications by executor group name, but executor group belongs to order, which belongs to application. Application -> Orders -> Executor group (Group).

Can anyone help me with this? Is it possible to sort by that deep object? Thanks.

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794
