### ISSUE TITLE
Apply predicate to a nested Arel node

### ISSUE THREAD

**Issue by ml** [activerecord-hackery/ransack#72]
I need to apply a predicate to a nested node. Is there any simpler way to achieve this than

``` ruby
class Candidate
  has_many :candidate_skills

  class FakeAttributeForIn
    def initialize(&block)
      @block = block
    end

    def in(args)
      @block.call args
    end
  end

  ransacker :skills_ids do |parent|
    FakeAttributeForIn.new { |args|
      cs = CandidateSkill.arel_table
      c = Candidate.arel_table

      CandidateSkill.where(cs[:skill_id].in(args).and(cs[:candidate_id].eq(c[:id]))).exists
    }
  end
end


Candidate.search(skills_ids_in: [1, 2, 3]).result

```

?

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794
