### ISSUE TITLE
Ransack breaks Rails 5 default belongs_to required: true behaviour

### ISSUE THREAD

**Issue by develop-test1** [activerecord-hackery/ransack#723]
More info here: https://github.com/rails/rails/issues/26557

**Comment by jonatack** [comment]
Right, so I just spent a few minutes reading your Rails issue. Turns out that you made them guess what the issue was and they had to investigate it -- without you having actually investigated it yourself or provided complete information. 

If you are willing to provide the information asked for in the Contributing Guide, including a full gist so we don't waste time trying to figure out how to reproduce your issue, then this can be re-opened.

**Comment by develop-test1** [comment]
Hello, @jonatack what information is missing?
Rails and Ruby version is specified, and ransack version is latest release from master branch.

**Steps to reproduce:**
Include `ransacker` gem in Gemfile.
User ransacker method in ActiveModel file i.e.:
`ransacker :status, formatter: proc { |v| statuses[v] }`
Use update method on invalid foreign_key (for record that doesn't exist) for belongs to association i.e:
`Post.update(author_id: 0)`

Expected behaviour:
ActiveRecord::RecordInvalid: Validation failed: Author must exist>"

Actual behaviour:
Post author_id is being updated with 0 value.

Rails 5 has `belongs_to required: true` set by default. However it appears that including ransack gem overrides this setting globally to `false` by default.

Please let me know if I can provide you with any additional information that would help resolve this issue.

**Comment by jonatack** [comment]
Please see [CONTRIBUTING.md](https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md), particularly steps 3 and 4.

**Comment by jonatack** [comment]
Anyone can jump in and investigate, but for me I'd like to insist on a standalone gist that demonstrates the issue is with Ransack and not elsewhere. Ransack is at the intersection of Ruby, Rails, Arel, Active Record, Mongoid and users' code, and many  issues like this one are not actually caused by Ransack.
