### ISSUE TITLE
Query : Intercepting default sorting mechanism 

### ISSUE THREAD

**Issue by shivabhusal** [activerecord-hackery/ransack#735]
Hey there, I have used `string` field to sort. The field consists of data like `5 AM`, `6 PM`. This is not working properly because for data like `11 AM` and `5 AM`, the `11 AM` comes first.

Is there a way I can intercept and modify the way it sends query?

thanks

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794
