### ISSUE TITLE
Associated model default scope applied, even when the association is unscoped

### ISSUE THREAD

**Issue by ninjarabbi** [activerecord-hackery/ransack#748]
I have a Video model with a default scope:

```
class Video < ActiveRecord::Base
  def self.default_scope
    where(enable: true)
  end
end
```

I have a User that has_many Videos, and I unscope that association because in that particular instance I want access to all videos, not only the enabled:

```
class User < ActiveRecord::Base
  has_many :added_videos, -> { unscope(where: :enable) }, class_name:'Video', foreign_key: 'added_user_id'
end
```
This works. When I use `User.find(1).added_videos` I get all the videos, not only the ones with `enable: true`

This breaks when I use an Active Admin filter in my User admin model:

`
  filter :added_videos_created_at, as: :date_range, label: 'Added Videos On'
`

When I activate it and try to filter users by when they added videos, it still tacks on the Video default_filter in the generated SQL:

`
SELECT DISTINCT COUNT(DISTINCT "users"."id") FROM "users" LEFT OUTER JOIN "videos" ON "videos"."added_user_id" = "users"."id" AND "videos"."enable" = $1 WHERE ("videos"."created_at" >= '2017-01-01 00:00:00.000000' AND "videos"."created_at" < '2017-01-05 00:00:00.000000')  [["enable", "t"]]`

I'm posting here because as I understand Active Admin uses ransack to do the actual query.

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794

**Comment by seanfcarroll** [comment]
Closed

**Comment by pioz** [comment]
I've same problem... unscope with ransack do not works.
