### ISSUE TITLE
Search for Array

### ISSUE THREAD

**Issue by ideaoforder** [activerecord-hackery/ransack#751]
Is there any way to write a custom predicate that will allow searching for an array, like:

```sql
SELECT `orders`.* FROM `orders` LEFT OUTER JOIN `order_items` ON `order_items`.`order_id` = `orders`.`id` WHERE (order_items.item_id, order_items.quantity) = (123, 1)
```

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794

**Comment by seanfcarroll** [comment]
Closed
