### ISSUE TITLE
Respect negative conditions for advanced collection associations

### ISSUE THREAD

**Issue by janklimo** [activerecord-hackery/ransack#752]
I was trying to use this functionality introduced in https://github.com/activerecord-hackery/ransack/pull/645 with conditional 2nd degree `has_many ... through` relationships with little success.

In my case:

- a Course `has_many :user_assigned_content_skills, -> { where(source: 'user') }, class_name: "ContentSkill"`
- and a ContentSkill `belongs_to :skill` and `belongs_to :course`

Then `Course.ransack({user_assigned_content_skills_skill_name_not_eq: 'ruby'}).result.to_sql` returns the following (i.e. false positives again if a course has multiple content_skills):

    SELECT courses.* 
    FROM courses 
    LEFT OUTER JOIN content_skills ON content_skills.course_id = courses.id AND content_skills.source = 'user' 
    LEFT OUTER JOIN skills ON skills.id = content_skills.skill_id 
    WHERE (skills.name != 'ruby')

Any ideas how to achieve this? Is there a plan to have it implemented in Ransack?

Many thanks for any insights!

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794
