### ISSUE TITLE
Whitelist predicates

### ISSUE THREAD

**Issue by faragorn** [activerecord-hackery/ransack#760]
I know that in Ransack there are ways to whitelist scopes, attributes for searching and sorting.
What would be the best way to hack in a feature to whitelist `predicates` on per attribute/model basis.
And is there a need for this feature in the gem itself?

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794
