### ISSUE TITLE
Wrong redirection link for multiple models in one controller action (form_helper)

### ISSUE THREAD

**Issue by naydenovg** [activerecord-hackery/ransack#763]
I am trying to use `sort_link` on a shared view, between a couple of models. What happens is that I send the correct ransack object, but I get redirected to different view.

Here is an example of what I do:

I have two models: `Foo` and `Bar`, with parent `Baz`

This is my controller:

```
class BazController 

  def index
    #params[:obj] contains the model
    @search = params[:obj].constantize.ransack(params[:search])
    @bars = @search.result.order('id DESC')
  end
end
```

routes:
```
resources :baz do
    collection do
      get '/foo', action: :index, as: 'foo',
                                   defaults: { attempts_obj: 'foo' }
      get '/bar', action: :index,
                                 as: 'bar',
                                 defaults: { attempts_obj: 'bar' }
```

view `sort_link @search, :created_at, 'Created at'`

What happens is when I am in `bar` view, it takes my `params` which are {obj: 'Bar', controller: 'baz', action: 'index'}, and uses `ActionView::RoutingUrl.url_for(params)` [here](https://github.com/activerecord-hackery/ransack/blob/master/lib/ransack/helpers/form_helper.rb#L127), which always finds the first route for `baz#index` which is `foo`.

However, `url_for` can also accept `String` as redirect url argument. Could you possibly extend `sort_link` to also accept redirect_url as an argument?

P.S. 

I have found temporary workaround for this.

```
def baz_sort_link(search, param, name = nil)
    link = sort_link search, param, name
    query = Rack::Utils.parse_nested_query(URI(Nokogiri::HTML(link).css('a')[0]['href']).query)
    path = public_send("#{search.klass.name.underscore}_baz_path", query)
    link_to link[/(?<=\>).+(?=<)/].html_safe, path
  end
```

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794
