### ISSUE TITLE
Provide additional arguments to scope

### ISSUE THREAD

**Issue by shir** [activerecord-hackery/ransack#769]
Hi. Is there a way to pass additional arguments to search scope. Here is example that I'm looking for:

```rb
class Client
  class << self
    def ransackable_scopes(_auth_object = nil)
      %i(filter_by_status)
    end

    def filter_by_status(status, context)
      case status
      when 'all'
        where(nil)
      when 'closed'
        where(%("status" == 'closed' OR id IN (:open_ids)), status: context[:user].try(:open_ids) || [])
      end
    end
  end
end

class ClientsController
  def index
    @q = Client.search(params[:q], context: { user: current_user }) # `context` or `additional_params` or `whatever`
    @clients = @q.result
  end
end
```

So I may pass additional argument from controller which I may use in scope.

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794
