### ISSUE TITLE
Multiple conditions on same combination of columns

### ISSUE THREAD

**Issue by dsounded** [activerecord-hackery/ransack#772]
Let's say I have one Rails model and it has_many others

`class A < ActiveRecord::Base`
`has_many :bs`
`end`

`class B < ActiveRecord::Base`
`end`

I have 2 conditions, I need all the records from A, which has relation in B with id: 1 and name(field in B table) equals 'b_1', and id: 2, and name 'b_2'

This doesn't work:

`A.ransack(g: [{bs_id_eq: 1, bs_name_eq: 'b_1'}, {bs_id_eq: 2, bs_name_eq: 'b_12}]`

because it performs a query like 

`"SELECT `as`.* FROM `as` LEFT OUTER JOIN `bs` ON `bs`.`a_id` = `a`.`id` WHERE (`bs`.`id` = 1 AND `bs`.`name` = 'b_1' AND `bs`.`id` = 2 AND `bs`.`name` = 'b_2')"`

so this is impossible, how to perform such a search ? Any ideas ?

**Comment by xlts** [comment]
@dsounded for what I understand you would like to run a query with an `IN` predicate. Have you tried the following? 
```ruby
A.ransack(bs_id_in: [1, 2], bs_name_in: ["b_1", "b_2"]).result
```
yields
```sql
SELECT "as".* FROM "as" LEFT OUTER JOIN "bs" ON "bs"."a_id" = "as"."id" WHERE ("bs"."id" IN (1, 2) AND "bs"."name" IN ('b_1', 'b_2'))
```

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794

**Comment by dsounded** [comment]
Could I take my time ? I will do the example a little bit later, please do not close it

**Comment by seanfcarroll** [comment]
Sure thing! I appreciate your comment.

**Comment by dsounded** [comment]
@seanfcarroll hello. sorry for delay

Here is a test repo and an example of find service with the comments describing the problem:

https://github.com/dsounded/ransack_example/blob/master/app/services/finder.rb

**Comment by TheDeadCode** [comment]
I am also having this problem - https://stackoverflow.com/questions/45126027/activerecord-querying-association-with-multiple-condition-pairs

It took 10 hours of googling to even find this issue. I'm subbing to the issue - hope it can be fixed.

Right now, if I take this: http://ransack-demo.herokuapp.com/users/advanced_search

It's impossible to only get records that have a blog title `starting with S AND R AND Q`. This means at least 3 blog posts must exist, each starting with one of those letters. (Strict has_many matching)

**Comment by letiesperon** [comment]
+1 I've also had this problem on multiple projects

**Comment by allanshin** [comment]
I'm running into this problem too, as can be demonstrated in this example advanced search https://ransack-demo.herokuapp.com/users/advanced_search

1) Posts.title -> starts with -> "a"
2) Posts.title -> starts with -> "b"

This should return the users that have multiple posts, with titles starting with "a" AND "b". But the SQL is wrong:
`SELECT "users".* FROM "users" LEFT OUTER JOIN "posts" ON "posts"."user_id" = "users"."id" WHERE ("posts"."title" ILIKE 'a%' AND "posts"."title" ILIKE 'b%')`

This will always return 0 results, since posts.title can never start with "a" AND "b" at the same time. I think a reasonable solution would be to LEFT OUTER JOIN the table with a different alias for as many times that the same column is searched (posts1, posts2, ... postsN) and then the field references that alias, so that the SQL is:

```
SELECT "users".* FROM "users" 
LEFT OUTER JOIN "posts" "posts1" ON "posts1"."user_id" = "users"."id" 
LEFT OUTER JOIN "posts" "posts2" ON "posts2"."user_id" = "users"."id" 
WHERE ("posts1"."title" ILIKE 'a%' AND "posts2"."title" ILIKE 'b%')
```

Another solution could be to split out into multiple queries that are then intersected:
```
SELECT "users".* FROM "users" LEFT OUTER JOIN "posts" ON "posts"."user_id" = "users"."id" WHERE ("posts"."title" ILIKE 'a%')
INTERSECT
SELECT "users".* FROM "users" LEFT OUTER JOIN "posts" ON "posts"."user_id" = "users"."id" WHERE ("posts"."title" ILIKE 'b%')
```

**Comment by deivid-rodriguez** [comment]
It's been a while since I don't play with AR and SQL, but I tried something like this:

```
ModelA.joins(:model_bs).where(model_bs: { model_a_id: 1, name: 'b_1' }).or(ModelA.joins(:model_bs).where(model_bs: { model_a_id: 2, name: 'b_2' })).to_sql
=> "SELECT \"model_as\".* FROM \"model_as\" INNER JOIN \"model_bs\" ON \"model_bs\".\"model_a_id\" = \"model_as\".\"id\" WHERE (\"model_bs\".\"model_a_id\" = 1 AND \"model_bs\".\"name\" = 'b_1' OR \"model_bs\".\"model_a_id\" = 2 AND \"model_bs\".\"name\" = 'b_2')"
```

Not sure whether it is what you wanted.

**Comment by dsounded** [comment]
@deivid-rodriguez It's hard to say, 3 years past :)

I have a feeling like yes, we can use `or` here, closing this one

**Comment by deivid-rodriguez** [comment]
Yeah, sorry I replied so late :sweat_smile:.

**Comment by alexeevit** [comment]
Just ran into this problem. So this seems to be impossible.

`A.ransack(g: [{bs_id_eq: 1, bs_name_eq: 'b_1'}, {bs_id_eq: 2, bs_name_eq: 'b_12}]`

The `or` doesn't help, because in the described case we need to get records A that have at least 2 records B:
- the first meets the conditions from the first group
- the second meets conditions from the second group.

With `or` it'd also select records A that have only 1 record B that meets one of the condition groups.

So I expect instead of this:
```
SELECT "as".* FROM "as"
LEFT OUTER JOIN "bs" ON "bs"."a_id" = "a"."id"
WHERE (
    "bs"."id" = 1 AND "bs"."name" =  'b_1' AND bs.id = 2 AND bs.name = 'b_2'
)
```

To have this:
```
SELECT "as".* FROM "as"
LEFT OUTER JOIN "bs" as "bs_1" ON "bs_1"."a_id" = "a"."id"
LEFT OUTER JOIN "bs" as "bs_2" ON "bs_2"."a_id" = "a"."id"

WHERE (
    "bs_1"."id" = 1 AND "bs_1"."name" =  'b_1'
    AND
    bs_2.id = 2 AND bs_2.name = 'b_2'
)
```

However, I don't think it's possible. Any ideas how to get this result? Custom scope or class method?
