### ISSUE TITLE
Can't include attribute without table into collection 

### ISSUE THREAD

**Issue by ducnguyenhuy** [activerecord-hackery/ransack#773]
hi,

I have 2 tables users and products. I want to show a list users and total of products of each user. So I need to use Ransack on model users and join with products to sum products and group by user_id. I have created alias for total of products `sum_products` but then I don't see ransack return that column in collection.

Could you please let me know why?

Thanks.

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794
