### ISSUE TITLE
.merge relation not working with ransack

### ISSUE THREAD

**Issue by dritir** [activerecord-hackery/ransack#774]
I have tested various scenarios, when you do something like:

`current_user.products.merge(Category.premium)`
or
`current_user.products.includes(:category).where(category: {type: "premium"})` 
 the output is a `Model::ActiveRecord_AssociationRelation`

Now, when passing `.ransack.result` it will duplicate many entries (based on the number of associated records), and when trying `distinct` it will give a SQL error.

 Everytime a  ::ActiveRecord_AssociationRelation is used with ransack it ends in the same problem, however `::ActiveRecord_Relation` and` ::ActiveRecord_Associations_CollectionProxy` works fine.
Shouldn't ransack work in the situation above?

What I did was:
 Created a `joins` that gave me `:ActiveRecord_Relation` used ransack, after the search and filter I included the model I needed.

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794

**Comment by dritir** [comment]
Will put it on StackOverflow

**Comment by seanfcarroll** [comment]
Closed.
