### ISSUE TITLE
Remove the attribute from f.attribute_fields while iterating in the view and include in a separate dropdown

### ISSUE THREAD

**Issue by pallavihegde1** [activerecord-hackery/ransack#776]
Is there a way to remove some attributes from the dropdown in the view??
I am basically trying to remove all the integer attributes and use it separately to give a dropdown for it.
If i remove the attribute from ransackable attributes i wont be able to use it in a separate dropdown too...

**Comment by seanfcarroll** [comment]
This issue appears more to be a HOW-TO issue rather than a bug in Ransack. We are in the process of cleaning up the Ransack gem and repo. If this issue is still relevant could you please ask it on StackOverflow?

If you think it is an issue with Ransack, please provide a repo with the issue and / or a pull request with failing tests. If you don't know how to do this, indicate it in the issue and we will look into it eventually.

Thank you

https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md

https://github.com/activerecord-hackery/ransack/issues/794
