### ISSUE TITLE
Bug in version 1.8.3: 

### ISSUE THREAD

**Issue by djleo95** [activerecord-hackery/ransack#803]
i'm using ransack 1.8.2 and in  order.rb i have:

```ruby
class Order < ApplicationRecord
  belongs_to :guest
  belongs_to :table, inverse_of: :orders

  has_many :order_dishes
  has_many :order_combos

  accepts_nested_attributes_for :guest
  accepts_nested_attributes_for :table

  def subtotal
    total_dishes_price = order_dishes.map{|order_dish| order_dish.valid? ?
      (order_dish.quantity * order_dish.price) : 0}.sum
    total_combos_price = order_combos.map{|order_combo| order_combo.valid? ?
      (order_combo.quantity * order_combo.price) : 0}.sum
    total_dishes_price + total_combos_price
  end
end
```

when i use rails console to test: 

```ruby
a = Order.new
a.save
=>success
```

but in 1.8.3
a.save => rollback
Please fix

**Comment by seanfcarroll** [comment]
Very strange ... I will look at it as soon as possible.

**Comment by JagdeepSingh** [comment]
@djleo i tried setting up the minimal application for above scenario using `rails` 5.1.2.

This statement:

```ruby
a = Order.new
a.save
=> false
```

returns `false` for both versions of `ransack`, 1.8.2, and 1.8.3. And is independent of ransack. Reason is because the `belongs_to` association cannot be left blank starting rails 5 (See error messages below).

```ruby
2.4.1 :004 > a.errors.full_messages
 => ["Guest must exist", "Table must exist"] 
```

What version of `rails` are you using?

**Comment by seanfcarroll** [comment]
Given this: " Reason is because the belongs_to association cannot be left blank starting rails 5 (See error messages below)."

Can we close this issue?

**Comment by djleo95** [comment]
Yeah sorry i didn't check this issue recently, thank you guys.
