### ISSUE TITLE
Removal of Ransack::Predicates.names_by_decreasing_length breaks ActiveAdmin 1.0

### ISSUE THREAD

**Issue by sriedel** [activerecord-hackery/ransack#888]
We recently updated Ransack from 1.8.4 to 1.8.7, and ActiveAdmin 1.0.0 broke.
Ransack::Predicates.names_by_decreasing_length got removed, but ActiveAdmin calls this in activeadmin-1.0.0/lib/active_admin/filters/humanized.rb:50, apparently in order to retrieve a list of defined predicates.

Could you re-add this function and remove it again with the next minor version bump?

**Comment by seanfcarroll** [comment]
@varyonic what do you think about this?

**Comment by varyonic** [comment]
I think @sriedel's options are to upgrade to ActiveAdmin 1.1 (which reworked humanized.rb in PR 4951) or stay with Ransack 1.8.4.

**Comment by seanfcarroll** [comment]
@sriedel you can lock your Ransack version in your gem file or upgrade to 1.1.

Closing.

**Comment by vinc** [comment]
Came here with the same issue, a bugfix update of Ransack unexpectedly broke our ActiveAdmin.

**Comment by gregmolnar** [comment]
@vinc Which versions were the problematic ones?

**Comment by vinc** [comment]
@gregmolnar we upgraded to 1.8.9 and it broke ActiveAdmin 1.0.0, so we reverted to 1.8.4 as suggested by @varyonic (thanks) and that fixed ActiveAdmin. This issue is easy to find from a search engine so it's an easy fix.

The only problem here was that the versioning and the changelog should have been more clear that this was a breaking change.

**Comment by varyonic** [comment]
For reference this change was proposed by an ActiveAdmin maintainer and discussed in [#820](https://github.com/activerecord-hackery/ransack/pull/820#discussion_r160449818)
